name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - scipy
  - ipython
  - jupyter
  - lxml
  - requests
  - enum34
  - click
  - click-datetime
  - nose
  - mock
  - coverage
  - urltools
  - pip
  - pip: 
    - statsmodels
    - pandas-datareader
    - finam-export
